// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmCyaig6smju6am4xoq0vzG8_3JLDI25U',
    appId: '1:1085106301733:web:55275bdb69654f4b3908cc',
    messagingSenderId: '1085106301733',
    projectId: 'rental-management-6d529',
    authDomain: 'rental-management-6d529.firebaseapp.com',
    storageBucket: 'rental-management-6d529.appspot.com',
    measurementId: 'G-EYVWQ3FSDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Rub8l5dv55EtwOtqPozAzgFxq1De2ks',
    appId: '1:1085106301733:android:4926501e9b0a0f143908cc',
    messagingSenderId: '1085106301733',
    projectId: 'rental-management-6d529',
    storageBucket: 'rental-management-6d529.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6RIfDQb2SI_n3fMGzVXT6XJ1cuOzPcOA',
    appId: '1:1085106301733:ios:c95fd59a0843e9223908cc',
    messagingSenderId: '1085106301733',
    projectId: 'rental-management-6d529',
    storageBucket: 'rental-management-6d529.appspot.com',
    iosBundleId: 'com.pro.rentalmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6RIfDQb2SI_n3fMGzVXT6XJ1cuOzPcOA',
    appId: '1:1085106301733:ios:f0cf1cd23fb585de3908cc',
    messagingSenderId: '1085106301733',
    projectId: 'rental-management-6d529',
    storageBucket: 'rental-management-6d529.appspot.com',
    iosBundleId: 'com.example.rentalManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmCyaig6smju6am4xoq0vzG8_3JLDI25U',
    appId: '1:1085106301733:web:1a3591415a14dadc3908cc',
    messagingSenderId: '1085106301733',
    projectId: 'rental-management-6d529',
    authDomain: 'rental-management-6d529.firebaseapp.com',
    storageBucket: 'rental-management-6d529.appspot.com',
    measurementId: 'G-PFTGSKHJ6C',
  );
}
